"""whatsapp por empresa

Revision ID: 272a4d7c8ccc
Revises: fbefaeff6281
Create Date: 2026-08-20 16:23:00.083238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272a4d7c8ccc'
down_revision: Union[str, Sequence[str], None] = 'fbefaeff6281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_accounts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('display_phone_number', sa.String(length=32), nullable=False),
    sa.Column('waba_id', sa.String(length=64), nullable=True),
    sa.Column('access_token_cifrado', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('verificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_accounts_phone_number_id'), ['phone_number_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_whatsapp_accounts_tenant_id'), ['tenant_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_accounts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_accounts_phone_number_id'))

    op.drop_table('whatsapp_accounts')
    # ### end Alembic commands ###
